services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27020:27017"
    networks:
      - mdm-net
    volumes:
      - mongo1-mdm:/data/db

  mongo-init:
    image: mongo:6.0
    container_name: mongo-init
    depends_on:
      - mongo1
    entrypoint: ["sh", "-c", "sleep 10 && mongosh --host mongo1 --eval '
      rs.initiate({ 
        _id: \"rs0\", 
        members: [
          { _id: 0, host: \"mongo1\" }
        ]
      })'"]
    networks:
      - mdm-net

  mdmbackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:${PORT}"
    environment:
      MONGODB_CONNECT: mongodb://mongo1:27017/MDM?directConnection=true&replicaSet=rs0
      ENTORNO: ${ENTORNO}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      UNIMUS_URL: ${UNIMUS_URL}
      UNIMUS_TOKEN: ${UNIMUS_TOKEN}
      SSH_HOST: ${SSH_HOST}
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mongo1
      - mongo-init
    networks:
      - mdm-net

networks:
  mdm-net:
    driver: bridge

volumes:
  mongo1-mdm: