services:
  mdmbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mdmbackend
    restart: always
    ports:
      - "3003:${PORT}"
    environment:
      MONGODB_CONNECT: ${MONGODB_CONNECT}
      ENTORNO: ${ENTORNO}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      UNIMUS_URL: ${UNIMUS_URL}
      UNIMUS_TOKEN: ${UNIMUS_TOKEN}
      SSH_HOST: ${SSH_HOST}
      SSH_USER: ${SSH_USER}
      SSH_PASSWORD: ${SSH_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_URL: ${RABBITMQ_URL}